/**
 * @purpose Expose the Velite-generated blog posts to the app in a ready-to-render shape.
 * @role    Thin selector layer over .velite output — filtering, sorting, lookup, date formatting.
 * @deps    ../../.velite (generated by velite.config.ts at build time).
 * @gotcha  No fs/parsing here — Velite already compiled everything. `date` is a full ISO datetime
 *          string; sort and format from that directly.
 */
import { posts, type Post } from "../../.velite";

export type BlogPost = Post;
export type BlogToc = Post["toc"];

/** Non-draft posts, newest first. */
export const publishedPosts: BlogPost[] = posts
  .filter((post) => !post.draft)
  .sort((a, b) => b.date.localeCompare(a.date));

export function getPostBySlug(slug: string): BlogPost | undefined {
  return publishedPosts.find((post) => post.slug === slug);
}

/** Format an ISO datetime as "Jul 10, 2026" (UTC, deterministic at build time). */
export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}
